//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asura.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asura.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   すべてのファイル(*.*)|*.*;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFilterAll {
            get {
                return ResourceManager.GetString("FileFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BMP画像形式(*.bmp)|*.bmp;*.BMP| に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFilterBMP {
            get {
                return ResourceManager.GetString("FileFilterBMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張メタファイルイメージ形式(*.emf)|*.emf;*.EMF| に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFilterEMF {
            get {
                return ResourceManager.GetString("FileFilterEMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GIF画像形式 (*.gif)|*.gif;*.GIF| に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFilterGIF {
            get {
                return ResourceManager.GetString("FileFilterGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JPEG画像形式(*.jpg)|*.jpg;*.JPG;*.jpeg;*.JPEG| に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFilterJPG {
            get {
                return ResourceManager.GetString("FileFilterJPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PNG画像形式(*.png)|*.png;*.PNG| に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFilterPNG {
            get {
                return ResourceManager.GetString("FileFilterPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TIFF画像形式 (*.tif)|*.tif;*.TIF;*.tiff;*.TIFF| に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFilterTIF {
            get {
                return ResourceManager.GetString("FileFilterTIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap InitialImage {
            get {
                object obj = ResourceManager.GetObject("InitialImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ファイルを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon proj_asura {
            get {
                object obj = ResourceManager.GetObject("proj_asura", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   ファイルを保存する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogTitle", resourceCulture);
            }
        }
    }
}
